### ISSUE TITLE
Icons not showing

### ISSUE THREAD

**Issue by Natanael1234** [nathanielw/Android-Lollipop-Pencil-Stencils#10]
Icons are not visible at Shapes menu:

![image](https://cloud.githubusercontent.com/assets/6856671/17779490/33e47bae-653e-11e6-8c78-5751d0bf5b8e.png)

Installed via Manage collections...->Install From Repository...

**Comment by nathanielw** [comment]
I'm not sure what's causing this. The icons show fine when installing via "Install From File..." but not when installing from the repository, so I'm fairly certain it's not a bug with the collection but rather a bug with Pencil. If you could report a bug over in the [Pencil repo](https://github.com/evolus/pencil/issues), that'd be good :smiley:
