### ISSUE TITLE
Not compatible with Pencil version 3.0

### ISSUE THREAD

**Issue by sunxfancy** [nathanielw/Android-Lollipop-Pencil-Stencils#14]
This stencils package is amazing, but it has some compatible errors. When I am using this package with Pencil version 3.0, all UI Icons are gone. There must be some errors after several times adding components. All kinds of the elements can not add again. Other additional packages run correctly.
Version: 3.0.0-rc.1

![screenshot 2017-01-17 16 04 19](https://cloud.githubusercontent.com/assets/6300305/22012517/5f543794-dccf-11e6-8758-7338a579f19f.png)

**Comment by peluprvi** [comment]
Reference of the same issue on Pencil:

https://github.com/evolus/pencil/issues/172
https://github.com/evolus/pencil/issues/178

**Comment by Erwinstein** [comment]
Sorry for the dumb question and bringing it up here, but how do you install a stencil in the first place? I've been searching for a way and for some reason, I can't find any.

**Comment by MonstroMart** [comment]
@sunxfancy Copy the content from the sub-folder found in the main install folder of the stencil to the main install folder (C:\Users\{username}\.pencil\stencils\v1.1.0_648_1490656627447\) and it will work. @toyongbanatero To install stencils click the manage collections icon right under the blue stencils bar and then click on the install from repository buton.

**Comment by nathanielw** [comment]
Closing as this is a duplicate (of #10 and #13) and is a bug in Pencil itself. From a quick test, it looks like the Pencil issue may have been fixed.
