### ISSUE TITLE
Error Installing on Pencil 3.0.4

### ISSUE THREAD

**Issue by lakuapik** [nathanielw/Android-Lollipop-Pencil-Stencils#19]
Hi,

I try to install this stencils to Pencil 3.0.4 an i got an error.

![img alt](http://i67.tinypic.com/1ghend.png "Error Installing Collection")

Is this stencils compatible with Pencil 3.0.4?

Thanks.

**Comment by mtangoo** [comment]
Any help? I face the same issue!

**Comment by mtangoo** [comment]
Actually I cannot install any stencil in created by @nathanielw 
I get the same error!

**Comment by nathanielw** [comment]
Hi all, would you be able to provide the exact steps you're following to install the collection? I'm unable to recreate the issue in Pencil 3.0.4 when installing via "Install from Repository" or "Install from File". If you're installing via the zip, make sure you're downloading the `android-lollipop-pencil-stencils-v1.1.0.zip` file, *not* the source zip.

**Comment by mtangoo** [comment]
Downloaded from https://pencil.evolus.vn/Downloads.html 
Mac Package. Trying to install `android-lollipop-pencil-stencils-v1.1.0.zip`

Here is how I import
![screen shot 2018-04-22 at 14 33 57](https://user-images.githubusercontent.com/1502872/39094614-d378d7c6-463a-11e8-98dd-844e741ec8a4.png)

**Comment by McGiogen** [comment]
It is possible to import the stencils also on Pencil 3.0.4.
1. Open the main menu -> Tools -> Manage Collections...
![Screenshot_20190903_181107](https://user-images.githubusercontent.com/2913644/64190534-e716ba80-ce76-11e9-8399-e25edd69b722.png)

2. Use the button "Install From File..." and select the downloaded "android-lollipop-pencil-stencils-v1.1.0.zip" file.
![Screenshot_20190903_181029](https://user-images.githubusercontent.com/2913644/64190525-e41bca00-ce76-11e9-9dc9-24d60ec64c49.png)

You will found them under the main "Shapes" tab (and not under "My Shapes").
