### ISSUE TITLE
Hard time finding an alternative to Pencil

### ISSUE THREAD

**Issue by abicelis** [nathanielw/Android-Lollipop-Pencil-Stencils#20]
Hi @nathanielw, long-time user of your lollipop stencils here,

I understand this repo is no longer being maintained. However, I am curious as to what software you are using now instead of Pencil, which seems now kinda dead, for your Android mockups.

Thanks!

**Comment by nathanielw** [comment]
Hey @abicelis, hopefully you've got some good use out of the stencils 😃 
Yeah, Pencil's development unfortunately seems to have stagnated a bit. I'm not doing quite as much mockup work myself anymore, but for the stuff I am doing I've been using [Figma](https://www.figma.com/). I've also heard good things about [Adobe XD](https://www.adobe.com/nz/products/xd.html) from workmates. 
Unfortunately I'm not aware of any open-source alternatives though - it feels like all the commercial options have shot ahead recently.

**Comment by nathanielw** [comment]
(closed for tidiness, but if anyone comes across this and has other alternatives to suggest, feel free to leave a comment)
