### ISSUE TITLE
Several components don't display correctly (or at all) in the Pencil Firefox extension

### ISSUE THREAD

**Issue by nathanielw** [nathanielw/Android-Lollipop-Pencil-Stencils#3]
Seems that svg elements with filters on them do not render in the Firefox extension version of Pencil.

**Comment by arifur** [comment]
The extensions does not work on the latest version of Firefox. I am not sure when it will be updated. So its better to stick with the actual application rather using the extension.

**Comment by nathanielw** [comment]
Solution found: in the **View** menu, make sure **Hide Heavy Elements** is unchecked.
