### ISSUE TITLE
Transparent element

### ISSUE THREAD

**Issue by arifur** [nathanielw/Android-Lollipop-Pencil-Stencils#4]
Some elements are transparent permanently. They do not have any background nor do they react to any changes to the background color change. Other elements do have background colors and react to color change

Some of the elements that have transparent backgrounds
1. Buttons
2. Floating Action Buttons
3. Card
4. Dialog 
5. Menu list

I am using Pencil 2.0.5 on Fedora 20 x64. I have tweaked almost all the options including opacity of individual element and collection, but neither helped.

**Comment by nathanielw** [comment]
Hi Arifur, thanks heaps for the info - I thought this issue just affected the Firefox version of Pencil (see: #3), but it looks like it happens on a fresh install of the standalone version as well.

I just found [this bug report](http://code.google.com/p/evoluspencil/issues/detail?id=207&q=shadow) which gives the solution: in the **View** menu, make sure **Hide Heavy Elements** is unchecked. Hopefully that fixes the issue for you as well. I'll have to look into how the default shapes manage to not disappear completely when their shadow is on and heavy objects are hidden.

**Comment by arifur** [comment]
Thank you. That solved the problem.

**Comment by OMARoun** [comment]
Le problème de l'ombre qui n’apparaît pas peut être résolu en désactivant la propriété **Hide Heavy Elements** dans le menu **View**.
![image](https://cloud.githubusercontent.com/assets/6178708/6997177/1308589e-dba9-11e4-845a-6d2b74c02d6c.png)
Merci beaucoup
