### ISSUE TITLE
thumbnails are not showing in menu

### ISSUE THREAD

**Issue by mwiacko** [nathanielw/Android-Lollipop-Pencil-Stencils#5]
I have zipped every file in main directory (definition, readme, icons, misc), imported  template , (install new collection) by selecting zipped definition. 

I'm new to pencil, but I'haven't found similar issue on pencil's repo.

I'm on windows 8.1

**Comment by nathanielw** [comment]
Just checking, when you say _"...zipped every file in main directory (definition, readme, icons, misc)"_ are you zipping all the files/folders into one zip or zipping each individual file/folder seperately?

You'll need to be zipping all the files/folders into one zip (so inside the zip there should be `definition.xml`, `icons/`, etc). If that's not working, it's probably easiest to figure out what's going on if you upload the zip somewhere so I can take a look.

(A few people have had trouble getting the collection installed, so I'm thinking I might add a pre-made zip to make things easier)

**Comment by mwiacko** [comment]
Ok, now everything is working. I was making zip files from files and directories (4 archives) presented in main folder. I hadn't understood why I must creating zip file if I already have one downloaded from github. Now everything is clear. Thanks for your reply
