### ISSUE TITLE
Install new collection

### ISSUE THREAD

**Issue by castrors** [nathanielw/Android-Lollipop-Pencil-Stencils#6]
Hi there, 

I'm having trouble with the installation and i don't know why. The message returned is: "Error isntalling collection".

I'm using Ubuntu 15.04, pencil 2.0.5. I tried to install some templates (here: http://pencil.evolus.vn/Stencils-Templates.html) and the importation finished with success.

**Comment by castrors** [comment]
I've extracted manually this project to the folder "/home/{USER}/.pencil/r3nd4i1v.default/Pencil/Stencils", and it works. Thanks.

**Comment by bhu1st** [comment]
Same error - "Error Installing Collection"

**Comment by nathanielw** [comment]
Which zip are you downloading from the [releases page](https://github.com/nathanielw/Android-Lollipop-Pencil-Stencils/releases)? Trying to install the source code zip will give an error, so make sure you're grabbing _android-lollipop-pencil-stencils-v1.0.0.zip_ file. I could probably make that clearer in the readme.

**Comment by castrors** [comment]
Yes @nathanielw, i used the clone project zip at the first time. Now i installed downloading by the releases page and it works perfectly. Thanks.

**Comment by nathanielw** [comment]
Great. I'll leave this issue open to remind me to update the readme instructions.
