### ISSUE TITLE
Shadows aren't working quite right

### ISSUE THREAD

**Issue by jwir3** [nathanielw/Android-Lollipop-Pencil-Stencils#7]
I've added this collection to pencil, and I've created several mockups of a screen I want to create. One thing I've noticed is that the Card image doesn't seem to have a shadow appropriate to the way it's displayed on an actual device (via the `cardElevation` property). Even if I check the 'Shadow' box in the properties of the object, I am left with flat looking cards in my mockup:

<img width="602" alt="screen shot 2016-02-02 at 1 19 38 pm" src="https://cloud.githubusercontent.com/assets/997106/12761222/a7d91d24-c9af-11e5-91f1-b872048464da.png">

**Comment by nathanielw** [comment]
Sounds like you might have Heavy Elements hidden. In the Pencil _View_ menu, make sure _Hide Heavy Elements_ is unchecked.

**Comment by jwir3** [comment]
Ah, you're right. Thanks!
