### ISSUE TITLE
Shadows?

### ISSUE THREAD

**Issue by mercmobily** [nathanielw/Android-Lollipop-Pencil-Stencils#9]
I am starting to use Pencil for mock ups. I am pretty useless at it!
Question: in the homepage, your mockup (the card) seems to have shadows. How do you do that?

**Comment by nathanielw** [comment]
It sounds like you might have heavy elements set to be hidden.
Make sure the _Hide Heavy Elements_ option in the _View_ menu is unchecked.

**Comment by mercmobily** [comment]
Ah, you are right! Another question... are you able, with these widgets, to set the height of a material widget? (normally you would have 5 layers) Thank you!

**Comment by nathanielw** [comment]
For now the shadows are either on or off unfortunately. I'm thinking about making a more generic material design collection for Pencil that would have that sort of thing, but it's not my top priority currently :smiley:
